name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with: { go-version: '1.24' }
      - name: Run unit tests
        run: go test -v ./...
      - name: Smoke test
        run: |
          echo 'Running smoke test...'
          terraform-ansible-inventory -i smoketest.json -f ansible \
            | grep -q "test1 ansible_host=192.168.1.10"
